config/routes.rb
OldPort::Application.routes.draw do

  root :to => "home#index"
  
  devise_for :users
    
  scope '/admin' do # scope the user admin pages so they don't conflict with devise
    resources :users do
      resources :orders
      resources :tests
    end
    resources :invitations
    resources :administrators
    resources :qr_codes do
      collection { post :import }
    end
  end
  
  get '/dashboard' => 'dashboard#index'
  get '/qr/:id' => 'qr#index'
  
  resources :results

  

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :invitable, :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :orders
  has_many :tests, :through => :orders
  
  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness:  true
  validates :address1, :city, :state, :country, presence: true, unless: Proc.new { |a| a.admin? }
  validates :control_number, numericality: { only_integer: true }, unless: Proc.new { |a| a.admin? }
  
  validates :password, length: { in: 8..128 }, on: :create
  validates :password, length: { in: 6..128 }, on: :update, allow_blank: true
  
  scope :customers, -> { where('role is null', active: true).order(:last_name, :first_name) } # note "->" is the same thing as "lamda" - very annoying
  scope :all_customers, -> { where('role is null').order(:last_name, :first_name) }
  scope :administrators, -> { where(role: 1, active: true).order(:last_name, :first_name) }
  scope :all_administrators, -> { where('role is not null').order(:last_name, :first_name) }
  
  ROLES = {:customer => nil, :super_administrator => 0, :administrator => 1}
  
  # default the user to active
  after_create do |u|
    u.update_attribute(:active, true) if u.active.nil?
  end
  
  def admin?
    !role.nil? 
  end
  
  def customer?
    role.nil?
  end
  
  def super_admin?
    role == ROLES[:super_administrator]
  end
  
  def destroy
    update_attribute(:active, false)
  end
  
  def active_for_authentication?
    super && active
  end

  def inactive_message
    "Sorry, this account has been deactivated."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :ensure_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.customers
  end

  def show
  end

  def new
    @user = User.new(:active => true, :country => 'United States')
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.invite!(current_user)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully invited.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new', alert:  @user.errors.inspect }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.active = false
    if @user.save
      redirect_to @user, notice: 'Customer was successfully deactivated.'
    else
      redirect_to @user, alert: 'Customer was not successfully deactivated.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :address1, :address2, :city, :state, :country, :role,
        :registration_number, :control_number, :issued_on, :expires_on, :active)
    end

end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name, :label => 'First Name' %>
    <%= f.input :last_name, :label => 'Last Name' %>
    <%= f.input :email %>
    <%= f.input :address1, :label => 'Mailing Address 1', :input_html => {class: 'required'} %>
    <%= f.input :address2, :label => 'Mailing Address 2' %>
    <%= f.input :city %>
    <%= f.input :state, :collection => STATES.invert, :selected => @user.state, :include_blank => true %>
    <%= f.input :country %>
    <%= f.input :registration_number, :label => 'State Caregiver/Dispensary Registration #' %>
    <%= f.input :control_number, :label => 'Control #' %>
    <%= f.input :issued_on, :label => 'Issued' %>
    <%= f.input :expires_on, :label => 'Expires' %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Orders</th>
      <th>Tests</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Orders', user_orders_path(user) %>
        <td><%= link_to 'Tests', user_tests_path(user) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Deactivate', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @user.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @user.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user.country %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<p>
  <strong>State Caregiver/Dispensary Registration #:</strong>
  <%= @user.registration_number %>
</p>

<p>
  <strong>Control #:</strong>
  <%= @user.control_number %>
</p>

<p>
  <strong>Issued:</strong>
  <%= @user.issued_on %>
</p>

<p>
  <strong>Expires:</strong>
  <%= @user.expires_on %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>