config/routes.rb
OldPort::Application.routes.draw do

  root :to => "home#index"
  
  devise_for :users
    
  scope '/admin' do # scope the user admin pages so they don't conflict with devise
    resources :users do
      resources :orders
      resources :tests
    end
    resources :invitations
    resources :administrators
    resources :qr_codes do
      collection { post :import }
    end
  end
  
  get '/dashboard' => 'dashboard#index'
  get '/qr/:id' => 'qr#index'
  
  resources :results

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user # customer
  has_many :tests
  belongs_to :creator, class_name: "User", foreign_key:  "created_by"
  
  after_create :create_tests
  
  validates :payment_type, :total, :quantity, presence: true
  validates :total, numericality: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
  
  PAYMENT_TYPES = ['Credit Card', 'Cash', 'PayPal', 'Other']

  def set_defaults
    self.quantity = 1
    self.total = 50
  end

  protected
  
  def create_tests
    self.quantity.times { self.tests.create(:user => self.user, :creator => self.creator) }
    logger.debug "I would create a test here this many times:  " << quantity.to_s
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
 
  before_filter :authenticate_user!, :ensure_admin
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_customer

  def index
    @orders = Order.where(:user => @customer)
  end

  def show
  end

  def new
    @order = Order.new
    @order.set_defaults
  end

  def edit
  end

  def create
    @order = @customer.orders.new(order_params)
    @order.creator = current_user
    respond_to do |format|
      if @order.save
        format.html { redirect_to user_order_path(@customer, @order), notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new', alert:  @order.errors.inspect }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to user_order_path(@customer, @order), notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @order.destroy
      redirect_to user_orders, notice: 'Order was successfully destroyed.'
    else
      redirect_to user_orders, alert: 'Order was not successfully destroyed.'
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end
    
    def set_customer
      @customer = User.find(params[:user_id].to_i)
      session[:customer_id] = @customer.id
    end

    def order_params
      params.require(:order).permit(:memo, :payment_type, :quantity, :total)
    end

end

app/views/orders/_form.html.erb
<%= simple_form_for(@order, url: (@order.new_record? ? user_orders_path(@customer) : user_order_path(@customer, @order))) do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
   	<%= f.input :quantity %>
   	<%= f.input :payment_type, :collection => Order::PAYMENT_TYPES, :selected => @order.payment_type, :include_blank => true %>
    <%= f.input :memo %>
    <%= f.input :total, :label => 'Total in USD' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', user_order_path(@customer, @order) %> |
<%= link_to 'Back', user_orders_path(@customer) %>

app/views/orders/index.html.erb
<h1>Listing Orders for <%= @customer.first_name %> <%= @customer.last_name %></h1>

<table>
  <thead align="left">
    <tr>
      <th>Order ID</th>
      <th>| Created At</th>	
      <th>| Quantity</th>
      <th>| Payment Type</th>
      <th>| Total</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody align="left">
    <% @orders.each do |order| %>
      <tr>
      	<td><%= order.id %></td>
      	<td>| <%= order.created_at %></td>
      	<td>| <%= order.quantity %></td>	
      	<td>| <%= order.payment_type %></td>
      	<td>| <%= order.total %></td>
      	<td>| <%= link_to 'View Tests', user_tests_path(@customer, :order_id => order.id) %></td>
        <td>| <%= link_to 'Show', user_order_path(@customer, order) %></td>
        <td>| <%= link_to 'Edit', edit_user_order_path(@customer, order) %></td>
        <td>| <%= link_to 'Destroy', "#", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_user_order_path(@customer) %>

app/views/orders/new.html.erb
<h1>New Order for <%=@customer.first_name %> <%=@customer.last_name %></h1>

<%= render 'form' %>

<%= link_to 'Back', user_orders_path(@customer) %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Order for <%= @customer.first_name %> <%= @customer.last_name %></h1>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Payment Type:</strong>
  <%= @order.payment_type %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @order.memo %>
</p>

<p>
  <strong>Total:</strong>
  <%= @order.total %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @order.created_at %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @order.creator.email %>
</p>


<%= link_to 'Edit', edit_user_order_path(@customer, @order) %> |
<%= link_to 'Back', user_orders_path(@customer) %>  |
<%= link_to 'View Tests', user_tests_path(@customer, :order_id => @order.id) %>