config/routes.rb
OldPort::Application.routes.draw do

  root :to => "home#index"
  
  devise_for :users
    
  scope '/admin' do # scope the user admin pages so they don't conflict with devise
    resources :users do
      resources :orders
      resources :tests
    end
    resources :invitations
    resources :administrators
    resources :qr_codes do
      collection { post :import }
    end
  end
  
  get '/dashboard' => 'dashboard#index'
  get '/qr/:id' => 'qr#index'
  
  resources :results

  

end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]
  before_action :ensure_super_admin

  def index
    @administrators = params[:all] ? User.all_administrators : User.administrators
  end

  def show
  end

  def new
    @administrator = User.new(:active => true)
  end

  def edit
  end

  def create
    @administrator = User.new(administrator_params)
    @administrator.role = User::ROLES[:administrator]
    if @administrator.save
      @administrator.confirm!
      redirect_to administrators_path, notice: 'Administrator was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @administrator.update(administrator_params)
      redirect_to administrators_path, notice: 'Administrator was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @administrator.active = false
    if @administrator.save
      redirect_to administrators_url, notice: 'Administrator was successfully deactivated.'
    else
      redirect_to administrators_url, alert: 'Administrator was no successfully deactivated.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def administrator_params
      params.require(:user).permit(:first_name, :last_name, :role, :email, :password, :password_confirmation, :active)
    end
    
    def ensure_super_admin
      redirect_to dashboard_path unless current_user.super_admin?
    end
end

app/views/administrators/_form.html.erb
<%= simple_form_for(@administrator, url: (@administrator.new_record? ? administrators_path : administrator_path(@administrator))) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<h1>Listing administrators</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Role</th>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.first_name %></td>
        <td><%= administrator.last_name %></td>
        <td><%= administrator.role %></td>
        <td><%= administrator.email %></td>
        <td><%= administrator.password %></td>
        <td><%= administrator.password_confirmation %></td>
        <td><%= administrator.active %></td>
        <td><%= link_to 'Show', administrator_path(administrator) %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Deactivate', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<h1>New administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @administrator.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @administrator.last_name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @administrator.role %>
</p>

<p>
  <strong>Email:</strong>
  <%= @administrator.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @administrator.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @administrator.password_confirmation %>
</p>

<p>
  <strong>Active:</strong>
  <%= @administrator.active %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>